CREATE TABLE public.bridges (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    note text,
    latitude double precision not null,
    longitude double precision not null,
    image_url text -- This will store the public URL to the image in Supabase Storage
);

-- Optional: Add comments for clarity
COMMENT ON COLUMN public.bridges.image_url IS 'Public URL of the image stored in the "bridges" Supabase Storage bucket.';