
CREATE TABLE public.user_profiles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    first_name text not null,
    last_name text not null,
    email text not null unique,
    phone text,
    location text,
    bio text,
    profile_image_url text
);

-- Optional: Add comments for clarity
COMMENT ON COLUMN public.user_profiles.profile_image_url IS 'Public URL of the profile image stored in Supabase Storage.';
